### PR TITLE
Add automatic zip creation

### PR DESCRIPTION
**Pull request by Davilarek**
This is currently a draft, if needed I can add functionality to automatically push to Firefox Addon store

### CODE REVIEW

**Comment by vzze** [comment]
Just creating the zip and placing it in the Releases section should be enough.

**Comment by Davilarek** [comment]
Okay

**Comment by Davilarek** [comment]
Done, should just work
You can see yourself on my fork, also, please note that the release creation time doesn't change, if needed I can try to find some workarounds that

**Comment by vzze** [comment]
Release creation time doesn't need to change, if it's done you can mark it for review

**Comment by Davilarek** [comment]
Yeah... So I've probably misread `Abort in case the git tag doesn't already exist in the remote repository` as `Abort in case the git tag already exists in the remote repository`. Sorry about that, removing --verify-tag should fix it

**Comment by vzze** [comment]
Doesn't seem to just work out of the box, does it need any additional setup?
I am not that familiar with github actions, if it seems dumb I'm sorry
image

**Pull request merged**
