### PR TITLE
add non-linear scaling option (fixes #8)

### LINKED ISSUE #8: Non-linear volume control
Hello, thanks for this great extension !

Do you think it would be relevant to have a non-linear scale for volume control ? I have to go down to about 10/100, which about halves the perceived volume (but this may vary between browsers / OSs).  I'll have a look at how this could be done in a few days.

Also I suggest you add the link to this repo in the description, so that it's easier to contact you (and also shows that the extension is open-source, which is great).

### PR DESCRIPTION
**Pull request by vzze**
adds a button bottom right which can toggle a non linear volume scale (`volume^2`)
edit: fixes #8

### CODE REVIEW

**Comment by vzze** [comment]
@sapristi if you want you can test the current patch locally, otherwise expect the feature to be live in 1-2 days

**Comment by sapristi** [comment]
Thanks :) however I don't see the button to toggle linear / non-linear

**Comment by vzze** [comment]
Just press on the text (graphics design is not my passion)

image

also make sure you don't have the addon installed from the firefox addon store while loading the extension locally

**Comment by sapristi** [comment]
I had forgotten to checkout the branch ^^'  

Tested, sounds good to me :)

**Pull request merged**
